swagger:
  host: 127.0.0.1:${server.port}
logging:
  level:
    com.yiwenyin.integral: DEBUG
    root: info
    org.springframework.web: info

spring:
  #设置数据库连接池
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/prune?useUnicode=true&characterEncoding=UTF8
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/prune?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: validate
      show-sql: true
server:
  port: 8810
